// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkicdlsiwiekyvhorntb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZraWNkbHNpd2lla3l2aG9ybnRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDkzODAsImV4cCI6MjA3MjEyNTM4MH0.nJQlfxfjnpgWlc0nOfUTfUQv84ncnoNzrH9-6X30TXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});